### ISSUE TITLE
Сложный запрос, лучше переписать его с inner join

### ISSUE THREAD

**Issue by voidlol** [EbiousVi/Ebious-Fridmor-DZ-3#1]
https://github.com/EbiousVi/Ebious-Fridmor-DZ-3/blob/cbcea93bcf281c41327262234d478d0664b29baa/pre-reform-dating-server/src/main/java/ru/liga/prereformdatingserver/service/repository/UserProfileRepository.java#L34-L52

**Comment by EbiousVi** [comment]
Еще сложнее сделал)))
