### ISSUE TITLE
А зачем тут pageble?

### ISSUE THREAD

**Issue by voidlol** [EbiousVi/Ebious-Fridmor-DZ-3#3]
https://github.com/EbiousVi/Ebious-Fridmor-DZ-3/blob/b161f21c84a73bb714f131109012d05863d7d26e/pre-reform-dating-server/src/main/java/ru/liga/prereformdatingserver/controller/FavouritesController.java#L28

**Comment by EbiousVi** [comment]
Рандомно попало)
