### ISSUE TITLE
Если уж есть ломбок, то используйте его везде

### ISSUE THREAD

**Issue by voidlol** [EbiousVi/Ebious-Fridmor-DZ-3#8]
https://github.com/EbiousVi/Ebious-Fridmor-DZ-3/blob/b161f21c84a73bb714f131109012d05863d7d26e/pre-reform-translator/src/main/java/ru/liga/prereformtranslator/service/dictionary/Dictionary.java#L1-L28

**Comment by EbiousVi** [comment]
Дядя Тагир Валеев на фоне рассказывал что Lombok это плохо. Я не знал что делать дальше!?

**Comment by EbiousVi** [comment]
Исправил, теперь он везде!
